import torch
from torch import nn 

# inputs will be:
    # image, tracks, (maybe labels?)

# output:
    # image-sized heatmap giving pixel-wise likelihoods of errors

# training data:
    # generated by active proofreading


# Maybe a mini U-net because the output is image sized? Def not full. Way too big!!